### ISSUE TITLE
Error in create.multiplex.default

### ISSUE THREAD

**Issue by jihunni** [alberto-valdeolivas/RandomWalkRestartMH#10]
Hello. 
I download RandomWalkRestartMH today and follow [RandomWalkRestartMH guidline](https://bioconductor.org/packages/release/bioc/vignettes/RandomWalkRestartMH/inst/doc/RandomWalkRestartMH.html). When I follow the command `PPI_MultiplexObject <- create.multiplex(list(PPI=PPI_Network))` as in a guide, `Error in create.multiplex.default(list(PPI = PPI_Network)) :   Layer 1 is not an igraph object` occurs. Could you check?

Thank you!

Jihun Jeung

**Comment by alberto-valdeolivas** [comment]
Hello @jihunni ,

Thanks for your interest in our package. Are you sure you are following all the steps? It is working fine for me and it also works in the internal runs of Bioconductor under Linux, Windows and Mac. 

```
library(RandomWalkRestartMH)
library(igraph)
data(PPI_Network)
PPI_MultiplexObject <- create.multiplex(list(PPI=PPI_Network))
```

Best regards,
Alberto
