### ISSUE TITLE
create.multiplexHetNetwork.topResults  does not work for weighted bipartite relationships

### ISSUE THREAD

**Issue by dkainer** [alberto-valdeolivas/RandomWalkRestartMH#8]
Hi, i get the following error when trying to generate a topresults object after running a MultiplexHet RWR:

```
Error in setnames(x, value) : 
  Can't assign 3 names to a 4 column data.table
```

I am pretty sure it is because my bipartite dataframe initially has 3 columns: 
node1 node2 weight

And within the create.multiplexHetNetwork.topResults function it is generating another column, "type", and then trying to assign only three column names to the bipartite dataframe when there are actually now four columns:

```
bipartite_relations$type <- bipartite_name
colnames(bipartite_relations) <- c("from", "to", "type")
```

**Comment by alberto-valdeolivas** [comment]
Hello! Sorry for the late reply, I was on holidays. Yeah, you are right, I did not change this funciton to allow a weigthed bipartite network. Indeed, the documentation still stands that the bipartite network should only contain two colums. I will take a look!

**Comment by alberto-valdeolivas** [comment]
Thanks again for pointing out to this issue. I just pushed a new version to solve it. Let me know if everything works fine for you now. 

Best regards,
Alberto.
